### ISSUE TITLE
Bug Found in Base32 Encode and Decode.

### ISSUE THREAD

**Issue by Xor-el** [KvanTTT/BaseNcoding#25]
Hello,
First of all, thanks for this nice Library, It has really been helpful.
I and my colleague @Ron4Fun found a bug in the encoding and decoding of certain values to Base32.
A test example is the Name "Ronald" without the quotes, verifying with other encoders gives "KJXW4YLMMQ======" but yours gives "KJXW4YLMMQ====" which is wrong.
I have fixed the issue in my Pascal Port but just decided to inform you about the bug.
I could provide a pull request if you want.
Regards.

**Comment by KvanTTT** [comment]
Of course welcome to make pull request! Thanks.

**Comment by Xor-el** [comment]
Pull Request Submitted.
