### ISSUE TITLE
inconsistance of "the compress ratio" between the system definition and the data in diagram.xlsx

### ISSUE THREAD

**Issue by e-cloud** [KvanTTT/BaseNcoding#27]
I find out something confusing between the system definition and the data in diagram.xlsx about the equation below.

![image](https://cloud.githubusercontent.com/assets/5255354/24329821/201d9ade-1244-11e7-825a-03ac435c48c5.png)

Take a exmpale(as Base64):

```
a=64
k=4
b=2
n=24

// then, according to the equation, ratio should be
r=64^4 / 2^24 =1
```

However, in the Diagram.xlsx:
![image](https://cloud.githubusercontent.com/assets/5255354/24329864/0954ef7c-1245-11e7-9745-44cd77b2e017.png)

Am i misunderstanding something?

@KvanTTT could you explain it? :smile: 

Anyway, really appreciate your awesome work.

**Comment by KvanTTT** [comment]
Thank you for remark!

I fixed math justification formula and updated a README. Actually, this Raio is a `r_bits` ratio in Diagram values table, but not `r_values` ratio.

For 64 case we got:
```
a=64
k=1
b=2
n=6
```

So, `r_bits = n/k = 6/1` and `r_values = a^k / b^n = 64^1 / 2^6 = 1`.

**Comment by e-cloud** [comment]
impressive update. However, i have to remind you that the first formula might be misspelled.
![image](https://cloud.githubusercontent.com/assets/5255354/24337403/41cec5dc-12cf-11e7-87e1-9f7073d0f207.png)
Shouldn't it be `a^k`?

**Comment by KvanTTT** [comment]
Thanks, you are right again! I fixed it too :)
