### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by ivaylo5ev** [KvanTTT/BaseNcoding#29]
Hi, I am interested in your code and I'd like to be able to consume the library as a nuget package. Do you have any official nuget package feed that can provide me with the package?

**Comment by KvanTTT** [comment]
Yes, I think it's possible.

**Comment by ivaylo5ev** [comment]
@KvanTTT , thanks for getting back to me. 

I usually feel more comfortable using third party code as a package. My primary concern is that the original authors of code I am using are properly attributed, and the best and most explicit way is trough a nuget package. 
The second best option in this regard is to add this repo as a submodule to my project. Since you don't feel ready to create a package, this is what I am going to do :)

Cheers
