### ISSUE TITLE
Binary encoding is worse than with `btoa`.

### ISSUE THREAD

**Issue by AlttiRi** [KvanTTT/BaseNcoding#32]
I have a 169 bytes image. Lets encode it.

Just run it in the browser console (on https://kvanttt.github.io/BaseNcoding/):
```js
let dataUrl = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAA+SURBVEhL7dIxCgAwCMVQ739pu/yh0JYgXfNWlSxWv9UhgwkDyAAygAygXEo/8k032dhkMGEAGUAGkAHQvQC3veR+Ql0lAQAAAABJRU5ErkJggg==`;
let base64 = dataUrl.slice("data:image/png;base64,".length);
let binaryString = atob(base64);

var alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
var baseN = new BaseN(alphabet, 64);
baseN.encodeString(binaryString);
```

#### The result is:
```
wolQTkcNChoKAAAADUlIRFIAAAAgAAAAIAgCAAAAw7wYw63CowAAAAFzUkdCAMKuw44cw6kAAAAEZ0FNQQAAwrHCjwvDvGEFAAAACXBIWXMAAA7DgwAADsODAcOHb8KoZAAAAD5JREFUSEvDrcOSMQoAMAjDhVDDr39pwrvDvMKhw5DCliBdw7NWwpUsVsK/w5UhwoMJA8OIADLCgAzCoFxKP8OyTTfDmcOYZDBhABlABsKQAcOQwr0AwrfCvcOkfkJdJQEAAAAASUVORMKuQmDCgC
```
`282` chars.

With "Base85" the length is `265`.

#### The expected result:
```
iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAA+SURBVEhL7dIxCgAwCMVQ739pu/yh0JYgXfNWlSxWv9UhgwkDyAAygAygXEo/8k032dhkMGEAGUAGkAHQvQC3veR+Ql0lAQAAAABJRU5ErkJggg==
```
`228` chars.  (`Math.ceil(169*4/3+2)`, `btoa(binaryString)`)

With "Base85" the length should be ~`212` (`169*5/4`).

---

Does it work as planned?

**Comment by KvanTTT** [comment]
Hi, I don't completely understand what are you trying to do. I have the same base64-encoded string both on my service and on https://www.base64encode.org/ for your input `iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAA+SURBVEhL7dIxCgAwCMVQ739pu/yh0JYgXfNWlSxWv9UhgwkDyAAygAygXEo/8k032dhkMGEAGUAGkAHQvQC3veR+Ql0lAQAAAABJRU5ErkJggg==`.

It's `aVZCT1J3MEtHZ29BQUFBTlNVaEVVZ0FBQUNBQUFBQWdDQUlBQUFEOEdPMmpBQUFBQVhOU1IwSUFyczRjNlFBQUFBUm5RVTFCQUFDeGp3djhZUVVBQUFBSmNFaFpjd0FBRHNNQUFBN0RBY2R2cUdRQUFBQStTVVJCVkVoTDdkSXhDZ0F3Q01WUTczOXB1L3loMEpZZ1hmTldsU3hXdjlVaGd3a0R5QUF5Z0F5Z1hFby84azAzMmRoa01HRUFHVUFHa0FIUXZRQzN2ZVIrUWwwbEFRQUFBQUJKUlU1RXJrSmdnZz09`

**Comment by KvanTTT** [comment]
It looks like you are performing double base-64 encoding using the following code:

```js
let dataUrl = `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAIAAAD8GO2jAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAA+SURBVEhL7dIxCgAwCMVQ739pu/yh0JYgXfNWlSxWv9UhgwkDyAAygAygXEo/8k032dhkMGEAGUAGkAHQvQC3veR+Ql0lAQAAAABJRU5ErkJggg==`;
let base64 = dataUrl.slice("data:image/png;base64,".length);
let binaryString = atob(base64);

var alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
var baseN = new BaseN(alphabet, 64);
baseN.encodeString(binaryString);
```

**Comment by AlttiRi** [comment]
I'm trying to encode the image (169 bytes) with Base85.

> I have the same base64-encoded string both on my service

You just encode base64 to base64.

`"iVBORw0..."` is not the input. The input is (`atob("iVBORw0...)`): base64 (input storing form) -> [binary string](https://gist.github.com/AlttiRi/836fc9b6d48b2e5b0ac334da9dfba62c) (raw input) -> base64.


----

Here is the image data:
```js
let ui8a = new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,32,0,0,0,32,8,2,0,0,0,252,24,237,163,0,0,0,1,115,82,71,66,0,174,206,28,233,0,0,0,4,103,65,77,65,0,0,177,143,11,252,97,5,0,0,0,9,112,72,89,115,0,0,14,195,0,0,14,195,1,199,111,168,100,0,0,0,62,73,68,65,84,72,75,237,210,49,10,0,48,8,197,80,239,127,105,187,252,161,208,150,32,93,243,86,149,44,86,191,213,33,131,9,3,200,0,50,128,12,160,92,74,63,242,77,55,217,216,100,48,97,0,25,64,6,144,1,208,189,0,183,189,228,126,66,93,37,1,0,0,0,0,73,69,78,68,174,66,96,130]);
```

---

Okay, lets start with base64.

Here is it the correct example with base64 received from `btoa`:
```js
function arrayBufferToBinaryString(arrayBuffer) {
    return arrayBuffer.reduce((accumulator, byte) => accumulator + String.fromCharCode(byte), "");
}
let binaryString = arrayBufferToBinaryString(ui8a);
btoa(binaryString); // correct base64, length is 228
```

With `BaseN`:
```js
var alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
var baseN = new BaseN(alphabet, 64);
baseN.encodeString(binaryString); // "base64", length is 282
```
The result is wrong.

**Comment by AlttiRi** [comment]
Well, I see why it happens. It treats the input string as a UTF-8 string.

While native [`btoa`](https://developer.mozilla.org/en-US/docs/Web/API/btoa) considers the input string as is, as a [binary string](https://gist.github.com/AlttiRi/836fc9b6d48b2e5b0ac334da9dfba62c). 
So I can represent `ArrayBuffer` (169 bytes) as a binary string (with `169` chars length) then _safely_ convert it to Base64 (228 bytes) with `btoa`.
